- .mergify.yml
> Fix mergify config to account for GitHub Actions checks

- CHANGES.rst
> Prepare release 1.0b4

- CHANGES.rst
- crate/operator/scale.py
- tests/test_scale.py
> Fix #84: Adjust parsing of replicas to use lower bounds

- crate/operator/config.py
- crate/operator/main.py
- tests/conftest.py
> Add missing timeout handling to bootstrap sub-handler

- README.rst
- docs/source/development.rst
Update docs and readme:
* Add note for macOS devs to the development guide.
* Add command to create the crate-operator namespace to the installation section of the readme.
> Update docs and readme

- .pre-commit-config.yaml
- crate/operator/backup.py
- crate/operator/bootstrap.py
- crate/operator/cratedb.py
- crate/operator/create.py
- crate/operator/kube_auth.py
- crate/operator/main.py
- crate/operator/scale.py
- crate/operator/utils/kubeapi.py
- tests/test_bootstrap.py
- tests/test_create.py
- tests/test_kubeapi.py
- tests/test_webhooks.py
> Bump test utilities in pre-commit

- tests/test_update_password.py
This will increase the stability of the tests in case handlers fail and need to be retried
> Wait a bit longer in user password tests

- CHANGES.rst
https://trello.com/c/Q2c1jsGC/74-cratedb-operator-final-release-10
> Prepare release v1.0

- docs/source/development.rst
Without the correct storage class, the tests would run into timeouts.
> Extend docs on how to use Minikube

- CHANGES.rst
> Prepare release 1.0.1

- docs/source/development.rst
- tests/conftest.py
- tests/test_bootstrap.py
- tests/test_create.py
- tests/test_resume.py
- tests/test_scale.py
- tests/test_update_password.py
- tests/utils.py
This reverts the change that introduced the local StorageClass. The SC seems to be causing issues in Azure, and the reasoning why it was introduced is unclear.
> Revert local StorageClass

- CHANGES.rst
> Prepare release 1.0.2

- crate/operator/create.py
- crate/operator/data/cratedb_max_shard-collector.yaml
- crate/operator/data/sql-exporter.yaml
- tests/test_create.py
> Added max-shards-per-node metric to the sql exporter

- CHANGES.rst
- Added a metric that reports the maximum allowed shards on a single node via SQL exporter.
- Reworked the set up of config files for the SQL exporter to make adding new metrics easier.
> Prepare release v1.1.0

- CHANGES.rst
> Prepare release 1.2.0

- .github/workflows/docker_image.yaml
> Fix docker_image github action

- CHANGES.rst
- crate/operator/main.py
There's been a significant amount of time and they are no longer used by anything.
This will require a 2.0 release as per SemVer.
> Remove deprecated annotations

- crate/operator/backup.py
- crate/operator/utils/kopf.py
- crate/operator/webhooks.py
- tests/test_webhooks.py
Send delay notifications when a snapshot is in progress and a operation
(scale/upgrade/restart) is triggered
> Enable sending delay notifications

- CHANGES.rst
> Prepare release 2.1.0

- CHANGES.rst
> Prepare release 2.3.0

- setup.py
> Fix it again to <=3.7.4 explicitly. < 3.8 was not enough.

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGES.rst
> Add the missing changelog entries and a new PR template.

- crate/operator/config.py
> Clarify the danger of setting a low LOG_LEVEL

- CHANGES.rst
> Prepare 2.7.0

- tests/test_metrics.py
When you run all the tests you have metrics for more than one cluster reported, who knew :)
> Fix a whoopsie with metric tests

- CHANGES.rst
> Prepare release 2.7.1

- CHANGES.rst
- crate/operator/operations.py
- crate/operator/utils/crate/__init__.py
- crate/operator/utils/crate/on.py
- crate/operator/webhooks.py
- tests/test_decorators.py
- tests/test_webhooks.py
Replace the error event by a feedback event and use it for a wider variety of notifications
> Add notifications during upgrade process

- CHANGES.rst
- crate/operator/create.py
Add mitigation for log4j vulnerability
> Add mitigation for log4j vulnerability

- CHANGES.rst
> Prepare release 2.8.0

- CHANGES.rst
- crate/operator/operations.py
- crate/operator/scale.py
- crate/operator/utils/notifications.py
Send notifications about the progress of a scaling operation to the API.
https://github.com/crate/cloud/issues/421
> Add notifications during scaling process

- CHANGES.rst
> Prepare release 2.9.0

- setup.py
Reverts crate/crate-operator#337
> Revert "Bump kubernetes-asyncio from 21.7.1 to 22.6.0"

- .pre-commit-config.yaml
- setup.py
Older version seems incompatible with the latest click.
> Upgrade black to latest

- CHANGES.rst
> Prepare release 2.11.0

- CHANGES.rst
- deploy/crd.yaml
Support k8s 1.22 API for cratedbs CRD.
> Support k8s 1.22 API for cratedbs CRD

- CHANGES.rst
> Prepare release 2.12.0

- CHANGES.rst
- crate/operator/handlers/handle_ping_cratedb_status.py
- crate/operator/handlers/handle_update_cratedb.py
- crate/operator/operations.py
- crate/operator/scale.py
- deploy/crd.yaml
- tests/test_scale.py
> Suspend clusters support

- CHANGES.rst
> Prepare 2.13.1

- CHANGES.rst
> Prepare release 2.13.2

- CHANGES.rst
> Prepare release 2.13.3

- crate/operator/handlers/handle_update_cratedb.py
This seems to speed up the tests somewhat as they don't need to wait as long when certain transient errors happen.
> Add explicit backoff to the cluster update handlers

- crate/operator/create.py
> Tolerate any if we can't remove tolerations

- CHANGES.rst
- crate/operator/change_compute.py
- crate/operator/create.py
- tests/test_change_compute.py
- tests/test_create.py
> When cpu or memory is changed tolerations now changes accordingly

- CHANGES.rst
> Prepare release 2.14.0

- .github/workflows/publish-helm-release.yaml
- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator-crds/README.md
- deploy/charts/crate-operator/Chart.yaml
- deploy/charts/crate-operator/README.md
- devtools/bumpversion.sh
- docs/source/development.rst
https://github.com/crate/cloud/issues/614
> add script to increment helm charts version

- README.rst
https://github.com/crate/cloud/issues/614
> Add Helm install in README

- CHANGES.rst
- crate/operator/config.py
- crate/operator/create.py
- crate/operator/handlers/handle_notify_external_ip_changed.py
- crate/operator/main.py
- crate/operator/utils/kubeapi.py
- tests/test_update_allowed_cidrs.py
- tests/utils.py
We didn't actually need it for testing, and it was using up another external IP, which are in short supply.
> Removed the testing load balancer.

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.15.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
- devtools/bumpversion.sh
> Prepare release 2.16.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.17.0

- .pre-commit-config.yaml
Update flake8 repo in pre-commit config
> Update flake8 repo in pre-commit config

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.19.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.20.0

- Dockerfile
> Bump setuptools to a version without security vulns

- CHANGES.rst
- crate/operator/config.py
use latest sql_exporter 0.9.2.
- [x ] Relevant changes are reflected in `CHANGES.rst`
> Use latest sql_exporter 0.9.2

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.21.0

- CHANGES.rst
- crate/operator/cratedb.py
- crate/operator/handlers/handle_restore_backup.py
- crate/operator/restore_backup.py
- crate/operator/webhooks.py
- tests/test_webhooks.py
> Cluster cloning restores admin username in CRD

- crate/operator/restore_backup.py
> Fixed tests not passing after restore backup pw reset fix

- crate/operator/restore_backup.py
Follow-up to https://github.com/crate/crate-operator/pull/452
There seems to be another possible state for `sys.shards` when the cluster ran out of disk space during a restore snapshot operation. shards of tables that have not even started to be restored seem to be there with `primary = FALSE` and `state = UNASSIGNED`. So we have 2 checks now:
- (the new) check if there is at least 1 shard with `primary = TRUE` for each table that should have been restored.
- (the already existing) check for primary shards in progress having `recovery['size']['percent'] < 100`
> Add check if shards exist for all restored tables

- .pre-commit-config.yaml
- setup.py
Just like in other projects, previous versions have been broken due to an update in poetry.
> Upgrade isort to latest

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.22.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.23.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/templates/cratedbs-cloud-crate-io.yaml
> Updated CRD to show the CPU requests and limits.

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.26.0

- .github/workflows/docker_image.yaml
- CHANGES.rst
Also took the time to update the versions of the various actions we use, as they were complaining about deprecated stuff.
> Build an arm64 image too

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.26.1

- CHANGES.rst
- crate/operator/config.py
Upgraded sql_exporter to new version that has arm64 support
> Upgraded sql_exporter so it will load on arm64 systems

- .github/workflows/add-to-project.yaml
This allows the cloud team (responsible for the operator in Crate.io) to triage and take action.
> Add an action that automatically adds all issues to the right project

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.27.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.28.0

- CHANGES.rst
- crate/operator/restore_backup.py
> Fixed a bug that prevented snapshots from being restored

- CHANGES.rst
- crate/operator/handlers/handle_ping_cratedb_status.py
- crate/operator/main.py
- crate/operator/prometheus.py
- tests/test_metrics.py
> Changed the metrics to also export the cluster name as a label.

- CHANGES.rst
- crate/operator/utils/kopf.py
https://github.com/crate/cloud/issues/1365
> Print exception details if an exception happens in a sub handler.

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.30.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.30.1

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.30.2

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.30.3

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.31.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.32.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.33.0

- CHANGES.rst
- setup.py
- tests/test_webhooks.py
> Bumped aiohttp to latest to fix CVE-2023-49081

- crate/operator/operations.py
> Fix grand central deployment test

- crate/operator/grand_central.py
Reduce memory of grand central api container
> Reduce memory of grand central api container

- .gitignore
- docs/source/index.rst
- setup.py
- Documentation: Use more recent Sphinx>=5
> Fix documentation and RTD builds

- crate/operator/grand_central.py
- tests/test_create.py
> Fixed Grand Central Prometheus annotation

- CHANGES.rst
- crate/operator/config.py
- crate/operator/grand_central.py
> Add grand central sentry dsn

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.34.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.34.1

- .github/PULL_REQUEST_TEMPLATE.md
> Add link to issue to PR template

- CHANGES.rst
- crate/operator/grand_central.py
https://github.com/crate/cloud/issues/1666
> Added the `Authorization` header to the allowed list for GC.

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.35.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.36.0

- CHANGES.rst
- crate/operator/constants.py
- crate/operator/create.py
Handle GCP provider
https://github.com/crate/cloud/issues/1556
> GCP: add initial support for provider and zone fetching

- CHANGES.rst
- crate/operator/bootstrap.py
- crate/operator/constants.py
- crate/operator/create.py
- crate/operator/grand_central.py
- crate/operator/handlers/handle_create_grand_central.py
- tests/test_create_grand_central.py
> Bootstrap gc_admin user

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.38.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.38.1

- CHANGES.rst
- crate/operator/grand_central.py
> Set an explicit ingress class for GC ingresses.

- CHANGES.rst
- crate/operator/config.py
https://github.com/burningalchemist/sql_exporter/releases/tag/0.14.2
Changelog: https://github.com/burningalchemist/sql_exporter/compare/0.11.1...0.14.2
> Upgrade sql_exporter to 0.14.2

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.39.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.40.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.40.1

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
- devtools/bumpversion.sh
> Prepare release 2.40.2

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.41.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.41.1

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.42.0

- CHANGES.rst
- docs/source/configuration.rst
> Clarify setting and usage of CLOUD_PROVIDER

- CHANGES.rst
> Add azure backup changelog

- CHANGES.rst
- crate/operator/config.py
> sql-exporter 0.16.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.43.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.43.1

- CHANGES.rst
- crate/operator/handlers/handle_create_cratedb.py
- crate/operator/prometheus.py
- docs/source/conf.py
- tests/test_metrics.py
commits from https://github.com/crate/crate-operator/pull/654
> Upgrade mypy

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.44.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.46.0

- CHANGES.rst
> Add changelog entry for kopf upgrade

- .github/workflows/main.yaml
- setup.py
Make the operator support Python 3.13.
> Maintenance: Add support for Python 3.13

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.47.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.47.1

- CHANGES.rst
- crate/operator/config.py
> sql_exporter: 0.18.0

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.50.0

- CHANGES.rst
- crate/operator/create.py
- tests/test_create.py
> Add `blobs.path` to STS

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Prepare release 2.51.0

- CHANGES.rst
- crate/operator/create.py
- tests/test_create.py
> Enable AWS cross-zone load balancing

- CHANGES.rst
- deploy/charts/crate-operator-crds/Chart.yaml
- deploy/charts/crate-operator/Chart.yaml
> Release 2.53.0
