tests/conftest.py
tests/test_operations.py
tests/test_scale.py
tests/utils.py

When the operator deploys a CrateDB cluster, the StatefulSet adds a
local PersistentVolume to each pod which can be used for debugging.
Historically, the operator used the "default" storage class for these
PVs. However, since "default" may map to block storages in the cloud,
e.g. on Azure or AWS, K8s would attempt to mount the same block device
onto multiple pods, which isn't possible. To mitigate the issue, the
operator's tests now ensure there's a local file system.

Make tests more resilient

---

CHANGES.rst
crate/operator/bootstrap.py
crate/operator/main.py
crate/operator/operations.py
crate/operator/scale.py
crate/operator/upgrade.py
crate/operator/utils/kubeapi.py
tests/conftest.py
tests/test_backup.py
tests/test_bootstrap.py
tests/test_create.py
tests/test_kubeapi.py
tests/test_operations.py
tests/test_scale.py

Previously, when instantiating any of the kubernetes-asyncio APIs, such
as `CoreV1Api`, we didn't pass in an explicit `api_client` instance,
causing a new one to be created each time, which then would never close
the connection.
To change that, the `ApiClient` is only ever instantiated inside
`main.yaml` and instances of the `AppsV1Api`, `CoreV1Api`, etc. are
passed to functions. The only exception is the `WsApiClient` which is
instantiated when needed to keep the load on the K8s cluster low, by
closing those long-running connections right away after use.

Close the K8s API client's connections

---

CHANGES.rst
crate/operator/create.py
docs/source/configuration.rst
tests/test_create.py

On the Node: The kubelet populates this with the zone information as defined by the cloudprovider. This will be set only if you are using a cloudprovider. However, you should consider setting this on the nodes if it makes sense in your topology.
-- [Docs: failure-domain.beta.kubernetes.io/zone](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone)

Support zone awareness on Azure

---

CHANGES.rst
crate/operator/create.py
tests/test_create.py

In order to allow CrateDB to route replicas in a reliable way, the
`zone` node attribute is set to the value of the Kubernetes pod's node
attribute `failure-domain.beta.kubernetes.io/zone` as documented in
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone
Refs #94

On Azure, pass the failure/fault domain to CrateDB nodes as `zone`

---

CHANGES.rst
crate/operator/main.py

Every now and then, the operator might get stuck when watching for events on the K8s API. By setting some timeouts this can be mitigated.
Refs https://github.com/nolar/kopf/issues/232
Refs https://kopf.readthedocs.io/en/latest/configuration/#api-timeouts

Set watch request timeouts

---

CHANGES.rst
crate/operator/upgrade.py

Fix #60: Update image of mkdir-heapdump init container on upgrade

---

CHANGES.rst
crate/operator/main.py
crate/operator/utils/kopf.py

To better identify annotations owned by the CrateDB Kubernetes Operator,
these annotations have been renamed accordingly.

Fix #101: Rename process, diff storage, and finalizer

---

.github/workflows/docker_image.yaml

This github action will trigger when a new tag is release and will build/publish/tag the docker image accordingly.
For a version like `1.0.0` or `1.0` there will also be a `latest` tag built, for versions like `1.0b1` there will not be a latest tag.

Add github action to build and publish docker images on new releases

---

crate/operator/backup.py
crate/operator/bootstrap.py
crate/operator/create.py
crate/operator/main.py
crate/operator/utils/kopf.py
setup.cfg
tests/conftest.py
tests/test_backup.py
tests/test_bootstrap.py
tests/test_create.py
tests/utils.py

Historically, the create handler for clusters was implemented in a
best-effort and with a bit of a "it'll be fine" approach. Kubernetes
resources were created and when they already existed that was fine. When
the create handler failed, though, the whole handler was being retried,
including the creation of already existing resources.
Now, with this change, only the individual sub-handlers will be retried,
making the process more efficient. The handler is now reentrant.
Unlike attempted in 07720e3080047c765211f6c56d70000b8b3a5043, the
ApiClient is now instantiated inside the individual sub-handlers, to
ensure a connection is available and open. Otherwise, sub-handlers will
fail with a `RuntimeError`: "Session is closed".
Refs #48
Refs 07720e3080047c765211f6c56d70000b8b3a5043

Ref #48: Make create handler more resilient

---

CHANGES.rst
deploy/crd.yaml
tests/test_create.py

With Kubernetes version 1.16, keys in objects would only be preserved
if they are either defined in the CustomResourceDefinition or if the
`x-kubernetes-preserve-unknown-fields` key in the object is set to
`true`. The following fields did not specify either keys or the magic
flag, thus never retained any value, rendering them useless.
* `.spec.cluster.settings`
* `.spec.nodes.data.*.annotations`
* `.spec.nodes.data.*.labels`
* `.spec.nodes.data.*.settings`
* `.spec.nodes.master.annotations`
* `.spec.nodes.master.labels`
* `.spec.nodes.master.settings`

Preserve keys in annotations, labels, and settings

---

CHANGES.rst
crate/operator/config.py
tests/conftest.py

Fix test configuration
* Parse the path of the kubeconfig to allow relative paths (e.g. `~/.kube/kube_config`)
* Update kube context check to consider the `--kube-context` argument.

Fix test configuration

---

docs/source/development.rst

Update testing docs
Add a note to point out that macOS users who use Minikube have to start a Minikube tunnel while running the integration tests.

Update testing docs

---

CHANGES.rst
crate/operator/create.py
tests/test_create.py

When using an AKS cluster created with `az aks create --zones 1 2 3`,
the various K8s nodes in different zones may share the fault domain.
That means, even if they are spread in different zones, and thus have a
high redundancy, that node attribute can't be used for replication
settings in CrateDB. Hence, using the zone attribute.

Use zone attribute instead of fault domain on Azure

---

CHANGES.rst
crate/operator/constants.py
crate/operator/main.py
tests/test_resume.py

Implement `@kopf.on.resume handler`.
The handler adds the `cloud.crate.io/user-password: true` label to each user's secret.
Story: https://trello.com/c/s8qWFI5L/102-8-password-recovery-for-cloud-clusters
Planning: https://github.com/crate/cloud-api/issues/1488

Implement @kopf.on.resume handler

---

CHANGES.rst
crate/operator/bootstrap.py
crate/operator/main.py
crate/operator/utils/kubeapi.py
tests/test_bootstrap.py

Update bootstrapping of the users to set the ``cloud.crate.io/user-password: true`` label to the secrets of each user.
Story: https://trello.com/c/s8qWFI5L/102-8-password-recovery-for-cloud-clusters
Planning: https://github.com/crate/cloud-api/issues/1488

Update bootstrapping of users to add label to secrets

---

CHANGES.rst
crate/operator/create.py
docs/source/configuration.rst
tests/test_create.py

Before this change, even if you specified a node.attr.zone parameter it would have been explicitly overridden by the operator.

Allow overriding node.attr.zone

---

docs/source/concepts.rst

Sphinx has an extension called "intersphinx"
(https://www.sphinx-doc.org/en/3.x/usage/extensions/intersphinx.html)
which allows cross-referencing multiple Sphinx projects. By relying on
the extension, dead links can be detected earlier. Additionally, it adds
the same semantics and contextual details for links between
documentation projects. For example, a link from the CrateDB Kubernetes
Operator docs to something in its code, would look like this:
```
:func:`crate.operator.main.create`
```
Linking to a function in another project, listed in the
`intersphinx_mapping` could be
```
:func:`kopf:kopf.on.create`
```
In both cases, Sphinx will know that it's linking to a function, thus
using the correct visual attributes when rendering the HTML. Unlike
linking to the URL directly, which would …

Use intersphinx links for links to the CrateDB docs

---

CHANGES.rst
crate/operator/cratedb.py
crate/operator/main.py
crate/operator/update_user_password.py
docs/source/concepts.rst
tests/test_update_password.py

Watch on Kubernetes Secrets that have the `operator.cloud.crate.io/user-password` label assigned and update the users of all CrateDB resources in the same namespace if the password changed.
Story: https://trello.com/c/s8qWFI5L/102-8-password-recovery-for-cloud-clusters
Planning: https://github.com/crate/cloud-api/issues/1488

Watch on Kubernetes Secrets and update user passwords if needed

---

deploy/rbac.yaml

Update permissions of the service account to be able to watch secrets.

Update permissions of the service account to be able to watch secrets

---

CHANGES.rst
crate/operator/backup.py
docs/source/configuration.rst

We want the backup jobs to notify us when they are complete (or failed). For this, pass on the webhook configuration that is already present in the operator to the created cronjob.
The params are passed as plain text variables since there's no obvious benefit in passing them as secrets (and it's much harder to do in a generic way).

Pass the webhook params to the backup job

---

CHANGES.rst
crate/operator/config.py
crate/operator/main.py
docs/source/configuration.rst

https://github.com/crate/crate-operator/issues/109

Make cluster_backup_image config optional

---

crate/operator/bootstrap.py
crate/operator/constants.py
crate/operator/operations.py
crate/operator/scale.py
crate/operator/update_user_password.py
crate/operator/utils/kubeapi.py
tests/test_bootstrap.py
tests/test_operations.py
tests/test_scale.py
tests/test_update_password.py
tests/utils.py

The [default value for backoff](https://github.com/nolar/kopf/blob/a6d302bbf1efc39e371167ed66dbbfadff8a66ca/kopf/reactor/handling.py#L21) is defined in Kopf as `1min`, which is the
same as the value we provided.
Therefore we can get rid of the `BACKOFF_TIME` constant and instead use
dedicated a `CONNECT_TIMEOUT` when creating new database connections and
a `DEFAULT_TIMEOUT` for tests.

Use default backoff time when raising TemporaryError

---

CHANGES.rst
deploy/crd.yaml

Since CrateDB accepts every string as a username we also don't want
that check in the crate-operator.

Remove username validation from the custom resource definition

---

CHANGES.rst
crate/operator/utils/kopf.py

Missing await meant we're not sending any notifications

---

crate/operator/create.py

Get the jmx_exporter from maven

---

CHANGES.rst
crate/operator/create.py

Changing it to "Local" keeps the IP address of the actual client connecting, instead of showing the node IP.

Change the external traffic policy

---

CHANGES.rst
crate/operator/backup.py
crate/operator/config.py
crate/operator/cratedb.py
crate/operator/main.py
crate/operator/operations.py
crate/operator/scale.py
crate/operator/utils/kopf.py
crate/operator/utils/state.py
deploy/rbac.yaml
tests/conftest.py
tests/test_operations.py
tests/test_scale.py
tests/utils.py

Before performing scaling/upgrading/restarts, check that:
1. There are any `CREATE SNAPSHOT ...` jobs in CrateDB. If so, waits for them to finish.
2. There is a running k8s job to perform the backup. If so, waits for it to finish. <- Note that this has to be done in addition to the `CREATE SNAPSHOT` check because there is a real possibility of a race condition - it might take up to 30s for the `CREATE SNAPSHOT` to appear once the backup job starts.
This is implemented as an additional state in the cluster update state machine - basically we block in the `ensure_no_backups` state until there are no backups running any more.
Also refactored the ITs somewhat to better reuse code (especially cluster creation).
Also fixed a bug that meant we're not waiting for a cluster to become GREEN before …

Prevent scaling/upgrading/restarting when a snapshot/backup is in progress

---

CHANGES.rst
crate/operator/backup.py
crate/operator/create.py
crate/operator/utils/kopf.py
tests/test_backup.py
tests/test_create.py
tests/utils.py

Handlers have a facility to store their status. That is stored in the "status" attribute of the resource that is being handled (CrateDB in our case). This was not working before, but is quite useful.
As a result of this change, some handlers had to be adapter to not return large representations (i.e. entire K8s resource objects), because these need to be serialiased and stored against the CrateDB resource (which obviously doesn't work).
The usage of these statuses allows some control of handler execution sequencing, because it is possible to check if a previous handler has succeeded or not, as described [here](https://kopf.readthedocs.io/en/latest/results/).

Allow returning a status from handlers

---

CHANGES.rst
crate/operator/create.py
deploy/rbac.yaml

A Pod Distruption Budget ensures that when performing Kubernetes cluster maintenance (i.e. upgrades), we make sure to not disrupt more than 1 pod in a StatefulSet at a time.

Add PDB for statefulset

---

CHANGES.rst

it's 2.0.0 because we've removed some backwards-compatible kopf annotations we no longer use since 1.0.0.

Prepare release 2.0.0

---

CHANGES.rst
tests/test_bootstrap.py
tests/test_update_password.py
tests/utils.py

New aiopg is actually raising a TimeoutError

---

setup.py

kopf depends on the latest, and 8.0.0 broke something that made kopf break in an un-expected way.

Fixing the version of click

---

docs/source/conf.py

kopf has moved on - the intersphinx documentation is broken because we're using
an older version of kopf that is no longer documented on readthedocs.

Ignoring missing kopf files in docs.

---

.gitignore
CHANGES.rst
crate/operator/edge.py
crate/operator/main.py
crate/operator/webhooks.py
tests/test_load_balancer_updates.py
tests/test_webhooks.py
tests/utils.py

This is required in the cloud to update DNS for Edge regions which do not run external-dns.

Send a webhook when an external IP is obtained

---

crate/operator/edge.py
crate/operator/main.py
crate/operator/webhooks.py

For most webhooks we don't care about them failing - they are simply FYIs about something working or not. Some others, OTOH, are important - i.e. an IP being obtained. These we want to be retried, so re-throw any exceptions that happen.
Also clarified some of the logging messages - namely do not need to log the name/namespace as these are always prepended by kopf.

Add ability to re-throw errors for webhooks

---

CHANGES.rst
tests/test_load_balancer_updates.py

Prepare 2.2.0 of the operator

---

CHANGES.rst
crate/operator/main.py

EKS does not use IP addresses and gives out hostnames to load balancers instead. The rest of our stack is prepared to deal with this, but not this handler.

Use the hostname if ip is not available

---

CHANGES.rst
crate/operator/create.py
tests/test_create.py

This enforces the distribution of the pods over the availability zones. By setting `when_unsatisfiable="DoNotSchedule", the pods will trigger the kubernetes autoscaler to add nodes to the cluster.

Use topologyspread instead of AntiAffinity Rules

---

CHANGES.rst
crate/operator/backup.py
crate/operator/cratedb.py
crate/operator/main.py
crate/operator/operations.py
tests/test_operations.py
tests/test_scale.py
tests/utils.py

Added a new kopf subhandler which updates the ``cluster.routing.allocation.enable`` setting to ``new_primaries`` before a cluster is upgraded, scaled up/down or restarted. This should disable shard allocations during this time. Once the process is finished the setting is reset to its default value by another subhandler.

Change cluster.routing.allocation.enable setting during upgrade

---

CHANGES.rst
crate/operator/backup.py
deploy/crd.yaml
tests/test_backup.py

This adds additional environment variables to the backup cronjob to be able to write to a custom S3 bucket.

Add additional env variable to cronjobs for custom s3 backup endpointUrl

---

CHANGES.rst
deploy/crd.yaml

Name, version number and number of nodes.
```
❯ k get cratedbs -A
NAMESPACE                              NAME                                   CLUSTERNAME          VERSION   NODES   AGE
ee397dc2-1678-4b4e-865f-390b9bfd348e   7a9b09de-82ad-4ee0-8797-d21e59fa410f   loose-ivory-ermine   4.6.3     3       18m
```

Update the CRD to print some additional info about the CrateDBs

---

CHANGES.rst
crate/operator/create.py
tests/test_create.py

The default of 60s is killing connections on long-running queries, which is not cool.
Fixes crate/cloud#312

Up the idle connection timeout to 1 hour

---

CHANGES.rst
crate/operator/create.py
crate/operator/main.py
tests/test_create.py

This allows to add IP addresses in CIDR notation to the crate service. Once defined, it allows connection to cratedb only from the specified IP ranges. 
cloud-234

Added service IP Whitelist to create.py

---

setup.py

A new one was released (3.8.0) that is incompatible with pytest-aiohttp. There is no newer version of pytest-aiohttp.

Fix version of aiohttp

---

crate/operator/__init__.py
crate/operator/config.py
crate/operator/handlers/handle_ping_cratedb_status.py
crate/operator/main.py
crate/operator/prometheus.py
setup.py

By default, on port 8080.
This also exposes cluster health metrics for each running cluster.
Once deployed, we can use this for the `CloudClusterHealthStatusError` and `CloudClusterLastSeenTooOld` alerts instead of using the API metrics.

Expose a Prometheus metrics endpoint

---

crate/operator/scale.py
docs/source/conf.py
setup.py

This is a WIP PR upgrading to the latest kopf. So far it seems that everything is compatible, but will need to be thoroughly tested. We are using one interface that is now protected (`from kopf._cogs.structs.diffs`).
References #217

Upgrading to the latest stable version of kopf

---

CHANGES.rst
crate/operator/handlers/handle_create_cratedb.py
crate/operator/handlers/handle_migrate_discovery_service.py
crate/operator/handlers/handle_migrate_user_password_label.py
crate/operator/handlers/handle_notify_external_ip_changed.py
crate/operator/handlers/handle_ping_cratedb_status.py
crate/operator/handlers/handle_update_allowed_cidrs.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/handlers/handle_update_user_password_secret.py
crate/operator/prometheus.py
tests/test_metrics.py

Prior to this change, metrics would "hang around" even if a cluster is deleted. This created a problem as deleted clusters would then trigger the LastSeenTooOld alert and 24x7.
The new method instead has a metric gatherer, which only reports metrics for clusters that exist. If a cluster is deleted, it's metrics will disappear in a few minutes and we won't get alerted.

Rework cluster health metric gathering

---

tests/conftest.py
tests/utils.py

This allows us to use non-default storage classes when running tests.

Allow overriding the storage class used in tests

---

CHANGES.rst
crate/operator/backup.py
crate/operator/bootstrap.py
crate/operator/config.py
crate/operator/constants.py
crate/operator/create.py
crate/operator/handlers/handle_create_cratedb.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/main.py
crate/operator/operations.py
crate/operator/scale.py
crate/operator/upgrade.py
crate/operator/utils/crate/__init__.py
crate/operator/utils/crate/on.py
crate/operator/utils/kopf.py
crate/operator/webhooks.py
setup.py
tests/test_decorators.py
tests/test_webhooks.py

This is a proposal how we could handle notifications to the API in case of exceptions or timeouts during an upgrade (or all other operations in the future). 
Added two `wrapt` universal decorators which can be applied to plain functions (for regular kopf handlers) or class methods (for subhandlers using StateBasedSubHandler). `@crate.timeout(timeout={seconds})` checks if the (sub)handler's runtime exceeded the given timeout seconds on each run and raises a `kopf.HandlerTimeoutError` in case it has timed out. This exception as well as all other `kopf.PermanentError`s are caught in `@crate.on.error(error_handler={my_error_handler})` and an error handler coroutine can be run sending notifications to the API. After that it re-raises the exception so it can be further processed by kopf.
This …

Add notifications for exceptions

---

CHANGES.rst
crate/operator/config.py
crate/operator/main.py

https://github.com/crate/cloud/issues/429 - Add timeouts to the main `update` and `create` handlers to make sure operations are not blocked forever by a subhandler which does not have an individual timeout.

Add timeouts to update and create handlers

---

CHANGES.rst
crate/operator/create.py

... busybox and similar images. This is wasteful in light of the new docker hub limits.

Changed ``imagePullPolicy`` on container init scripts to not always pull

---

CHANGES.rst
crate/operator/config.py
crate/operator/constants.py
crate/operator/create.py
crate/operator/expand_volume.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/operations.py
crate/operator/utils/formatting.py
tests/test_create.py
tests/test_expand_volume.py
tests/utils.py

In the cratedb update handler we check now which value of the data nodes has changed. If `replicas` changed, we perform the scaling as usual. If `resources.disk.size` changed, we start three new subhandlers:
1) `SuspendClusterSubHandler` checks if the cluster is healthy before starting the whole process and scales the sts down to 0 replicas
2) `ExpandVolumeSubHandler` patches all PVCs whose name starts with `data` to the new disk size and continuously checks if the real value from `status.capacity.storage` equals the desired new disk size in `resources.requests.storage` OR if the PVC has the `FileSystemResizePending` condition. It keeps doing that for a configurable amout of time - currently 30 minutes. If it does not match after that, we assume the underlying storageclass provisioner …

Expand volumes of existing clusters

---

setup.py
tests/test_expand_volume.py

The check if the `cluster_update` handler has been finished starts earlier because `_all_pvcs_resized` check only checks if the PVC has been patched and finishes faster than the `expand_volume` subhandler really succeeds or times out. Increasing the timeout to 5min should fix it.

Fix expand volume test

---

CHANGES.rst
crate/operator/create.py

Change the value of ``when_unsatisfiable`` in the ``TopologySpreadConstraint`` to
``ScheduleAnyway`` to be able to deploy a cluster with more than 3 nodes again.

Fix topology spread constraint

---

crate/operator/expand_volume.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/operations.py
crate/operator/scale.py

This reverts commit e59064715d4e6a139f850dbe239ca6e508fb35e0.
Was needed because the commit introduces a bug where the success webhook is never sent for suspend/resume operations

Revert "Suspending sends the right message when in progress

---

crate/operator/expand_volume.py
crate/operator/operations.py

Temporarily update status notification message, so it can be used for both operations, volume expansion and suspend clusters.

Update suspend cluster status notification message

---

setup.py

Incompatible.
Reverts crate/crate-operator#368

Revert "Bump kubernetes-asyncio from 21.7.1 to 23.6.0"

---

CHANGES.rst
crate/operator/operations.py
tests/test_scale.py

Fixed a bug in the check if the backup metrics deployment has been scaled down successfully, or rather if the `backup-metrics` pod is gone. The `crate-snapshot` pods in the same namespace have the same labels, so the operation to suspend a cluster would have been stuck as long as such a pod was present
```
Handler 'cluster_update/scale' failed temporarily: Waiting for backup metrics pods [{'uid': '719c8f9f-743c-497e-aceb-7b46ba98edeb', 'name': 'create-snapshot-7987a175-ea95-445d-995f-43378fe3a16d-276252qd6z'}] to match desired number of replicas 0
```
https://github.com/crate/cloud/issues/702

Fix a bug that would cause suspending a cluster to get stuck

---

CHANGES.rst
crate/operator/handlers/handle_update_user_password_secret.py
crate/operator/update_user_password.py

We were sending this prematurely, regardless of whether the update succeeded or not.

Only send notification once actually succeeded

---

CHANGES.rst
crate/operator/config.py
crate/operator/main.py
docs/source/development.rst
setup.py
tests/conftest.py
tests/test_create.py
tests/test_upgrade.py
tests/utils.py

This is done using pytest-xdist and by adding the `-n X` parameter to pytest, where X is the number of parallel executors.
This required a locking mechanism to be implemented, as each worker spawns it's own operator (in the `kopf_runner` fixture). If the tests detect that they are running in parallel mode, the operator will only process the CrateDBs that have the `{"testing": "$PID"}` annotation - meaning that they will only process CrateDBs from the same worker. This allows us to continue using various `@mock.patch` monkey-patches that assume there's just one process running.

Added support for parallel testing

---

CHANGES.rst
crate/operator/create.py
tests/test_create.py

While looking into https://github.com/crate/cloud/issues/807 we found that we need to change to type of AWS Loadbalancer to type `NLB`. Without this annotation it is created as type `CLASSIC`, which does not support AWS private endpoints.

Add service annotation

---

CHANGES.rst
Dockerfile

... run command in the Dockerfile. This fixes a warning that the operator prints when starting.

Added the `-A` option (all-namespaces) to the operator

---

CHANGES.rst
crate/operator/data/cratedb_cluster_last_activity-collector.yaml
crate/operator/data/cratedb_cluster_last_user_activity-collector.yaml
crate/operator/data/sql-exporter.yaml

https://github.com/crate/cloud/issues/589

Added cratedb_cluster_last_activity metric to the sql exporter

---

crate/operator/data/cratedb_cluster_last_user_activity-collector.yaml
crate/operator/data/cratedb_max_shards-collector.yaml

Before:
```
cratedb_cluster_last_user_activity{cratedb_cluster_last_user_activity="cratedb_cluster_last_user_activity"} 1.665733388e+09
```
After:
```
cratedb_cluster_last_user_activity 1.665733888e+09
```

Remove the redundant labels

---

CHANGES.rst
crate/operator/change_compute.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/operations.py
crate/operator/scale.py
crate/operator/upgrade.py
crate/operator/utils/kopf.py
crate/operator/utils/notifications.py
tests/test_change_compute.py
tests/test_expand_volume.py
tests/test_scale.py
tests/test_upgrade.py

Fixed success notifications being sent too soon for update operations

Fixed success notifications being sent too soon for update operations

---

README.rst

The CRD, when printing `kubectl get cratedbs` shows the number of "hot" nodes. 
This is also what CrateDB Cloud uses by default.

Change the node name to "hot"

---

CHANGES.rst
crate/operator/config.py
crate/operator/expand_volume.py
crate/operator/handlers/handle_update_cratedb.py
docs/source/configuration.rst
tests/conftest.py

This is controlled by the ``NO_DOWNTIME_STORAGE_EXPANSION`` config option and defaults to false. The feature must be supported by the underlying infrastructure, i.e. Azure AKS or AWS EKS supports it using CSI drivers.
https://github.com/crate/cloud/issues/917

Added support for expanding volumes online (without suspending the cluster)

---

CHANGES.rst
crate/operator/handlers/handle_update_cratedb.py
tests/conftest.py

This was causing issues on Azure AKS. Will now first suspend the cluster and only then attempt to resize volumes.

Disabled parallel cluster suspension and volume resizing

---

CHANGES.rst
crate/operator/handlers/handle_update_user_password_secret.py
crate/operator/update_user_password.py

To avoid passwords getting out of sync if a user changes it directly in CrateDB (`ALTER USER`), we change the way the new password is set to do it directly on the pod using `crash`

Use crash to update user password

---

CHANGES.rst
crate/operator/create.py

Set TopologySpreadConstraint to DoNotSchedule. We changed this sometime ago in https://github.com/crate/crate-operator/pull/363, it did not allow to schedule Statefulsets >3. The behavior seems different now (`1.22.15`) and seems to avoid situations where Pods are scheduled on to the same availability group.

Set TopologySpreadConstraint to DoNotSchedule

---

CHANGES.rst
crate/operator/config.py
crate/operator/cratedb.py
crate/operator/handlers/handle_restore_backup.py
crate/operator/main.py
crate/operator/operations.py
crate/operator/restore_backup.py
crate/operator/utils/kopf.py
deploy/charts/crate-operator-crds/templates/cratedbs-cloud-crate-io.yaml
tests/test_restore_backup.py
tests/test_scale.py
tests/utils.py

This change allows restoring a backup from a different source crateDB cluster into another crateDB cluster. To trigger this operation, an object called `spec.cluster.restoreSnapshot` has to be created in the cratedb crd e.g. like this 
```yml
restoreSnapshot:
accessKeyId:
secretKeyRef:
key: access-key-id
name: restore-from-backup-{target_cluster_id}
basePath:
secretKeyRef:
key: base-path
name: restore-from-backup-{target_cluster_id}
bucket:
secretKeyRef:
key: bucket
name: restore-from-backup-{target_cluster_id}
secretAccessKey:
secretKeyRef:
key: secret-access-key
name: restore-from-backup-{target_cluster_id}
snapshot: "{snapshot_name}"
tables:
- all
```
Also the secret called `restore-from-backup-{target_cluster_id}` in the target cluster's namespace containing `bucket`, `base-path`, …

Add support for restoring clusters from a backup

---

CHANGES.rst
crate/operator/update_user_password.py
tests/test_update_password.py

Fixed update admin password sometimes sending false succeeded webhook

Fixed update admin password sometimes sending false succeeded webhook

---

CHANGES.rst
crate/operator/create.py

Apparently 1.36 was erroneously marked as 'latest' whereas it is unstable -> https://github.com/docker-library/busybox/issues/162

Downgrade busybox to previous version

---

CHANGES.rst
crate/operator/cratedb.py
tests/test_cratedb.py

Add `sys.node_checks` to the health query

Improve cluster healthiness query

---

CHANGES.rst
crate/operator/cratedb.py
tests/test_cratedb.py

Looks like that for the operator tests, we need to fix some issues.
```
psycopg2.errors.InternalError_: UNION [DISTINCT] is not supported
```

Fix union for operator tests

---

CHANGES.rst
crate/operator/handlers/handle_update_cratedb.py

Do not perform cluster pre-flights checks when expanding disk.

No pre-flight check on PVC expand

---

CHANGES.rst
crate/operator/backup.py
crate/operator/create.py
crate/operator/operations.py
crate/operator/utils/typing.py
tests/test_backup.py
tests/test_scale.py
tests/utils.py

```
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1
Warning: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

Deprecated APIs for pdb and batch

---

CHANGES.rst
crate/operator/create.py
crate/operator/handlers/handle_create_cratedb.py
deploy/charts/crate-operator-crds/templates/cratedbs-cloud-crate-io.yaml
tests/test_create.py

This is useful when, i.e., wanting to override the type of load balancer to be used.

Added an ability to specify additional annotations for the created LoadBalancer services.

---

.github/CODEOWNERS
CHANGES.rst
README.rst
crate/operator/bootstrap.py
crate/operator/handlers/handle_create_cratedb.py
deploy/charts/crate-operator-crds/templates/cratedbs-cloud-crate-io.yaml
tests/test_bootstrap.py
tests/test_upgrade.py
tests/utils.py

The operator will no longer attempt to set a license, even if one is configured in the CRD. Licenses are deprecated since CrateDB 4.5, and are about to be removed in the next CrateDB minor version.

Removed handling of licenses.

---

CHANGES.rst
crate/operator/create.py
crate/operator/operations.py
crate/operator/utils/kubeapi.py
tests/test_expand_volume.py
tests/test_scale.py

Suspending/resuming a cluster takes down / creates the load balancer

---

CHANGES.rst
tests/test_expand_volume.py
tests/test_upgrade.py
tests/utils.py

They were impacted by the fact that we're not deleting the load balancer. So now we explicitly wait for the update handler to finish before we query the hostname.

Fixed PVC resize tests.

---

.readthedocs.yml

Proactively update Read the Docs environment to compensate for recent release of urllib3 2.x, otherwise failing on an incompatibility with older OpenSSL versions.
```
Could not import extension sphinx.builders.linkcheck (exception:
urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module
is compiled with OpenSSL 1.0.2n  7 Dec 2017.
See: https://github.com/urllib3/urllib3/issues/2168)
```

RTD: Update to Ubuntu 22 and Python 3.9

---

CHANGES.rst
crate/operator/constants.py
crate/operator/data/cratedb_unreplicated_tables-collector.yaml
crate/operator/data/sql-exporter.yaml
crate/operator/main.py
crate/operator/operations.py
tests/test_metrics.py

- export metric `cratedb_unreplicated_tables` if there are (partitioned) tables with 0 replicas in the cluster
- add a `kopf.on.resume` handler which adds this metric to all `crate-sql-exporter` configmaps
https://github.com/crate/cloud/issues/959

Add cratedb_unreplicated_tables metric to sql exporter

---

CHANGES.rst
crate/operator/restore_backup.py

Setting `max_restore_bytes_per_sec` from default (`40mb`) to `240mb`.
https://crate.io/docs/crate/reference/en/5.3/sql/statements/create-repository.html#sql-create-repository

Change `max_restore_bytes_per_sec` to `240mb`

---

tests/conftest.py
tests/test_expand_volume.py

We use this by default now in CrateDB Cloud, so makes sense to test with it too.

Using no-downtime storage expansion in tests

---

CHANGES.rst
crate/operator/handlers/handle_ping_cratedb_status.py
crate/operator/prometheus.py
tests/test_metrics.py

We use the `exported_namespace` label because `namespace` is scraped automatically from wherever the operator just so happens to live in.
**Note:** not merging yet as our prometheus setup ignores this label for some reason. Will figure it out.

Changed the metrics to also export the namespace as a label

---

CHANGES.rst
crate/operator/config.py
crate/operator/data/sql-exporter.yaml

We want to switch to the latest available version and increase the concurrency settings in the sql_exporter configuration.

Bump sql_exporter to 0.11.1

---

CHANGES.rst
crate/operator/operations.py

Update only `data` of the `sql-exporter` configmap. This should fix the occasional `409 Conflict` error in the tests when also `resourceVersion`, `creationTimestamp` and `uid` are tried to be patched.

Update only data of sql-exporter configmap

---

CHANGES.rst
crate/operator/main.py
crate/operator/operations.py

Fixed deleting a cluster while restoring/cloning

---

CHANGES.rst
crate/operator/restore_backup.py

Fixes https://github.com/crate/cloud/issues/1362

Increase timeout for querying snapshots table

---

CHANGES.rst
crate/operator/create.py

Looking at you, AWS NLB.
https://github.com/crate/cloud/issues/1473

Explicitly lowering TCP keepalives to 120s to deal with naughty load balancers

---

CHANGES.rst
crate/operator/utils/version.py

Updated the ``CrateVersion`` nightly parsing to accept the new datetime format of ``yyyy-mm-dd-hh-mm`` while still being compatible with the old ``yyyymmdd`` format.

Update nightly version comparison

---

CHANGES.rst
crate/operator/change_compute.py
crate/operator/constants.py
crate/operator/create.py
crate/operator/utils/crd.py
crate/operator/webhooks.py
deploy/charts/crate-operator-crds/templates/cratedbs-cloud-crate-io.yaml
tests/test_change_compute.py
tests/test_create.py

Add optional `nodepool` to the node's CRD and set node affinity and tolerations accordingly when creating a cluster or changing its compute.
https://github.com/crate/cloud/issues/1502

Add `nodepool` to the CRD

---

crate/operator/grand_central.py
crate/operator/operations.py
setup.py
tests/test_scale.py
tests/utils.py

- Suspend and resume grand central `Deployment` when a cluster is suspended/resumed
- Use the `system` user in gc to connect to crateDB
- Increased the initial delay to avoid crashes while crateDB is starting up
- Pinned `alabaster` version, because the latest does not work with our version of `Sphinx`
https://github.com/crate/cloud/issues/1619

Suspend and resume grand central Deployment when a cluster is suspended/resumed

---

CHANGES.rst
crate/operator/constants.py
crate/operator/grand_central.py
crate/operator/handlers/handle_create_cratedb.py
crate/operator/handlers/handle_update_allowed_cidrs.py
crate/operator/handlers/handle_upgrade_grand_central.py
crate/operator/main.py
crate/operator/operations.py
deploy/charts/crate-operator-crds/templates/cratedbs-cloud-crate-io.yaml
deploy/charts/crate-operator/templates/rbac.yaml
deploy/rbac.yaml
setup.py
tests/test_create.py
tests/test_scale.py
tests/test_update_allowed_cidrs.py
tests/utils.py

This adds an optional section `grandCentral` to the CrateDB CRD which (if configured) creates the resources (deployment, service, ingress) for grand-central backend when deploying a cluster. `grandCentral` section looks like this
```yaml
grandCentral:
backendImage: cloud.registry.cr8.net/crate/grand-central:latest
backendEnabled: true
apiUrl: https://console.cratedb-dev.cloud/
jwkUrl: https://console.cratedb-dev.cloud/api/v2/meta/jwk/
```
https://github.com/crate/cloud/issues/1590

Deploy grand central backend

---

crate/operator/grand_central.py

Grand Central has a scheduler running. The scheduler does not support sharing a job store, so we must wait for one GC to stop before starting another one.

Disallow rolling upgrades

---

setup.cfg

This way we do not have to use the annoying `@pytest.mark.asyncio` annotation everywhere.

Change pytest async mode to auto

---

CHANGES.rst
crate/operator/bootstrap.py

... which returns a slightly different version of `UserAlreadyExistsException` (`RoleAlreadyExistsException`) and breaks bootstrap.

Fixed compatibility with CrateDB 5.6

---

CHANGES.rst
crate/operator/bootstrap.py
crate/operator/update_user_password.py

Updated user modification operations to leverage parameterized queries and
``curl``, replacing direct usage of ``crash``. Might also want to replace the remaining ``crash`` queries. ``crash`` unfortunately doesn't support parameterized queries.
resolves: https://github.com/crate/cloud/issues/1671

Updated user modification operations to leverage parameterized queries

---

CHANGES.rst
crate/operator/grand_central.py

Add `GRAND_CENTRAL_API_URL` env var to the gc deployment, required for sending webhooks.
https://github.com/crate/cloud/issues/1606

Add grand central api url env var

---

CHANGES.rst
crate/operator/change_compute.py
crate/operator/config.py
crate/operator/main.py
crate/operator/operations.py
crate/operator/upgrade.py
crate/operator/utils/crate/on.py
crate/operator/utils/kopf.py
tests/test_decorators.py

Moved timeout handling from the main `cluster_update` handler to the individual subhandlers. Therefore it is necessary to store the timestamp when each subhandler really started working somewhere (in the status object in this case).
It has a better granularity and allows to have for example a timeout after 24h for the pre-upgrade tasks and I kept 2 hours for the upgrade itself).
Code based on https://github.com/crate/crate-operator/pull/473
https://github.com/crate/cloud/issues/1621

add timeout to cluster update handlers

---

CHANGES.rst
crate/operator/config.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/main.py
crate/operator/operations.py
tests/test_restore_backup.py
tests/test_scale.py
tests/utils.py

The `AfterClusterUpdateSubHandler` is now split in two. The first one is as it used to be and the second one is to re-enable the cronjob.
This new handler is not added to the `depends_on` list because it can be delayed by 1h in some cases. It means that the success notification will be sent and the handler will be executed later (if an issue occur, the `error` decorator will do the trick). 
The delay is applied if `delay_cronjob=True` is in the status. It is set to True in the `upgrade` handler.

Delayed cronjob re-enabling after cluster upgrade/resume

---

CHANGES.rst
crate/operator/create.py
crate/operator/grand_central.py
crate/operator/handlers/handle_create_cratedb.py
crate/operator/handlers/handle_create_grand_central.py
crate/operator/main.py
tests/test_create_grand_central.py

Moved the creation of grand central resources from cluster creation process to a separate handler, because it actually has no dependencies on other handlers. This allows installing grand central also for existing clusters by adding a section like this to the CRD:
```yaml
grandCentral:
backendImage: cloud.registry.cr8.net/crate/grand-central:latest
backendEnabled: true
apiUrl: https://console.cratedb-dev.cloud/
jwkUrl: https://console.cratedb-dev.cloud/api/v2/meta/jwk/
```

Add separate handler to create grand central resources

---

CHANGES.rst
crate/operator/utils/crate/on.py

This fixes a bug that subhandlers were erroneously considered to be timed out because the check if a handler has timed out did not consider the handler's ref when fetching the start time. So e.g. operations like suspend/resume which both use the `ScaleSubHandler` were immediately marked as timed out and failed.

Fix calculation of subhandler runtime

---

CHANGES.rst
crate/operator/grand_central.py

... that explicitly waits for the associated CrateDB to be started.
:warning: requires latest grand central image.

Added an init container for grand central

---

crate/operator/utils/kubeapi.py
tests/test_create_grand_central.py
tests/test_load_balancer_updates.py
tests/test_update_allowed_cidrs.py
tests/utils.py

This fixes the failing tests when starting a cluster with gc enabled is blocked and hence timing out.

Try to fix gc tests

---

CHANGES.rst
crate/operator/backup.py
crate/operator/bootstrap.py
crate/operator/change_compute.py
crate/operator/constants.py
crate/operator/create.py
crate/operator/expand_volume.py
crate/operator/grand_central.py
crate/operator/handlers/handle_ping_cratedb_status.py
crate/operator/handlers/handle_update_allowed_cidrs.py
crate/operator/handlers/handle_update_user_password_secret.py
crate/operator/main.py
crate/operator/operations.py
crate/operator/prometheus.py
crate/operator/restore_backup.py
crate/operator/scale.py
crate/operator/upgrade.py
crate/operator/utils/k8s_api_client.py
crate/operator/webhooks.py
tests/conftest.py
tests/test_metrics.py

- Share k8s api client and set a hard limit for max TCP connections
- Remove the `sql-exporter` configmap check on resume
- Remove requests to retrieve the sts and ns in the health pings

Set a hard limit for max TCP connections

---

CHANGES.rst
setup.py

trivy scan was failing recently https://jenkins.crate.io/job/devops/job/docker-build-publish/4956//console

Upgrade aiohttp to 3.9.5 for CVE-2024-30251

---

CHANGES.rst
crate/operator/grand_central.py

We continue to see occasional crash due to OOMs especially on clusters with frequent scheduled jobs.
Also reduce CPU limit to 500m as we're too generous with 2 CPUs now.

GC: increase memory to 256Mi and drop CPU limit to 500m

---

CHANGES.rst
crate/operator/create.py
tests/test_create.py

Please note this branch does not disable the node.attr.zone as originally intended as a security mitigation, but rather
fixes the issue by adding support to AWS IMDSv2, which requires a token and a header in order to successfully perform
HTTP requests on the magic IP ``169.254.169.254``.
Also note the change made still supports IMDSv1, so a smooth transition in the infrastructure side can be done once all
CrateDB clusters have been patched.
Additionally, added a missing test for GCP for the ``node.attr.zone`` generation.

Changed the CrateDB parameter node.attr.zone for AWS to support IMDSv2

---

CHANGES.rst
crate/operator/create.py

Add explicit security context capability for compatibility with cri-o

---

CHANGES.rst
crate/operator/bootstrap.py
crate/operator/config.py
crate/operator/cratedb.py
crate/operator/create.py
crate/operator/grand_central.py
crate/operator/handlers/handle_create_grand_central.py
crate/operator/handlers/handle_restore_backup.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/operations.py
crate/operator/restore_backup.py
crate/operator/upgrade.py
crate/operator/utils/jwt.py
crate/operator/utils/kubeapi.py
tests/test_cratedb.py
tests/test_create.py
tests/test_upgrade.py
tests/utils.py

This change enables JWT authentication for crateDB version `5.7.2` and above
- adds the following settings to the crate command in the StatefulSet
```
"-Cauth.host_based.config.98.method": "jwt",
"-Cauth.host_based.config.98.protocol": "http",
"-Cauth.host_based.config.98.ssl": "on",
```
- sets the JWT config for the `admin` user when a new cluster is deployed
- restricts access for the `admin` user to the `gc` schema
- updates the JWT config for the `admin` user after upgrading (or restoring a snapshot) to a version that supports JWT by running an `ALTER USER` with `crash`

Add configuration for JWT authentication

---

CHANGES.rst
crate/operator/update_user_password.py
tests/test_update_password.py

This is a workaround for updating user passwords for crateDB versions that support JWT authentication (>= `5.7.2`).
First, the user's JWT config is reset with `ALTER USER "{username}" SET (jwt = NULL);` and after that it is set back to what it was before (`iss` is retrieved from the CRD) together with the updated password.
For older crateDB versions the password update remains unchanged.

Fix password update for users with jwt

---

CHANGES.rst
crate/operator/kube_auth.py
setup.py
tests/test_create.py

Upgrade kubernetes-asyncio to `31.1.0`.

kubernetes-asyncio upgrade to 31.1.0

---

CHANGES.rst
crate/operator/create.py

This help Cluster Autoscaler to provision nodes in zone which are set to 0 nodes.
Require at least 3 nodes (as we have 3 zones)
https://kubernetes.io/blog/2023/04/17/fine-grained-pod-topology-spread-features-beta/#kep-3022-min-domains-in-pod-topology-spread

TopologySpreadConstraints: add minDomains=3

---

CHANGES.rst
crate/operator/cratedb.py
crate/operator/operations.py
crate/operator/update_user_password.py

This includes a fix for upgrades getting stuck on clusters without a `users` config. It also adds some checks that could potentially cause issues for clusters without `grandCentral`.

Fix JWT auth handlers for clusters without users

---

.github/workflows/main.yaml

Intended to toggle the badge on the Build Status page [^1] into green.
[^1]: https://cratedb.com/docs/crate/clients-tools/en/latest/status.html

CI: Update GHA configuration to also run on the `master` branch, and stacked PRs

---

setup.py

Update package versions for Sphinx and friends.
Also, make them more lenient in order to support a broader range of Python versions.
https://crate-operator--674.org.readthedocs.build/
- GH-636

Documentation: Update Sphinx dependencies

---

CHANGES.rst
crate/operator/grand_central.py
tests/test_create_grand_central.py

This change sets CORS annotations for ingress-nginx in the `grand-central` ingress to the same values we also use in the crate command in the StatefulSet. This is for
- dev: `https://console.cratedb-dev.cloud,http://localhost:8000`
- prod `https://console.cratedb.cloud`

Update cors annotations in grand-central ingress

---

CHANGES.rst
crate/operator/change_compute.py
tests/test_change_compute.py
tests/utils.py

**Improve Resource Requests and Limits Handling** for `start_cluster` function. And also change the jvm `-CProcessor` setting which should reliably report the number of CPUs available in a docker environment. 
- **Updated `start_cluster` Function:**
- Modified to accept both `resource_requests` and `resource_limits` as separate parameters.
- Ensured proper handling and application of these resources when initializing clusters.
- **Refactored `utils.py`:**
- Corrected conditional checks to accurately apply resource limits and requests.
- Enhanced error handling for missing resource specifications.
- **Enhanced Test Cases in `test_change_compute.py`:**
- Fixed asynchronous calls by properly awaiting the `start_cluster` coroutine, as the test now needs to pull in the crate container …

Update `-Cprocessors` on scale compute

---

CHANGES.rst
crate/operator/restore_backup.py
tests/test_restore_backup.py

This adds support for quoting schema and table names when generating the keyword for restoring a snapshot.
E.g. restoring a snapshot with `croud` and `... --type tables --tables doc.table-with-dashes,doc.my-table ...` results in `... TABLE "doc"."table-with-dashes","doc"."my-table" ...` in the generated command.

Quote schema and tables names in restore snapshot

---

CHANGES.rst
crate/operator/data/sql-exporter.yaml

`min_interval` set `0` runs the queries on every scrape. Setting it to `60s` avoids to run them too often and results are returned from cache.

Change sql_exporter min_interval

---

.github/workflows/main.yaml
.pre-commit-config.yaml
.readthedocs.yml
CHANGES.rst
Dockerfile
crate/operator/config.py
docs/source/conf.py
docs/source/crate_operator_ext.py
docs/source/development.rst
setup.cfg
setup.py
tests/utils.py

Thanks a lot for your work @amotl! 
I cherry-picked your commit from GH-675 and updated mypy to a newer version - not the latest one though. I thought a gradual approach might be better to keep things smoother and tackle changes incrementally without adding too much all at once.
So I would leave GH-654 open for now and address it once we tackle the upgrade to Python 3.11. wdyt?

Update to Python 3.10

---

CHANGES.rst
crate/operator/cratedb.py
tests/test_restore_backup.py

`SELECT grantee FROM sys.privileges where grantor = 'system' limit 1`
has been replaced by
`SELECT grantee FROM sys.privileges where grantor = 'system' and grantee != '{GC_USERNAME}' limit 1"`
in order to never return the GC username instead of the admin one.
It will need to be changed in the future when some new roles will be added (e.g. `developer`, `viewer`, etc).

Fixed get_cluster_admin_username when grand-central is enabled

---

CHANGES.rst
crate/operator/grand_central.py

Newer versions of Nginx [1.12+](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.12.0) has annotation security checks enabled, and the [sizeRegex](https://github.com/kubernetes/ingress-nginx/blob/0374af94ef9cbf2b50aa57ae8ae68c7dbafec290/internal/ingress/annotations/parser/validators.go#L57) does not allow `i` in the value.

Update nginx proxy-body-size annotation value

---

CHANGES.rst
crate/operator/config.py
crate/operator/data/cratedb_cluster_last_user_activity-collector.yaml

Also fix warning about metric being NULL:
```
level=WARN source=query.go:226 msg="Value column is NULL" logContext="collector=cratedb_cluster_last_user_activity_collector,query=cratedb_cluster_last_user_activity" column=cratedb_cluster_last_user_activity-collector
```

Update sql_exporter to 0.17.0

---

CHANGES.rst
crate/operator/create.py
tests/test_create.py

With the move to AlmaLinux 10 base image the `rev` util is not present anymore.

Switch to awk for zone and node name extraction

---

crate/operator/main.py

Attempt to fix 429 TooManyRequests errors from the Kubernetes API.

Increase backoff interval between watching requests

---

CHANGES.rst
crate/operator/config.py
crate/operator/create.py
crate/operator/handlers/handle_create_cratedb.py
crate/operator/upgrade.py
tests/test_create.py
tests/test_scale.py
tests/test_upgrade.py
tests/utils.py

This ensures that default global JWT authentication settings are added to the CrateDB command when:
- Deploying new clusters with version >= `5.10.1`
- Upgrading existing clusters to CrateDB version >= `5.10.1`
https://cratedb.com/docs/crate/reference/en/master/config/node.html#jwt-defaults

Enable global jwt settings in CrateDB 5.10.1+

---

.github/workflows/main.yaml
setup.py

Make the operator support Python 3.11.

Maintenance: Add support for Python 3.11

---

.readthedocs.yml
CHANGES.rst
Dockerfile
crate/operator/config.py
docs/source/conf.py
docs/source/development.rst

This PR upgrades Python to `3.11` to stay in line with the kopf `1.36.2` upgrade, which also moves to Python `3.11`

Update to Python 3.11

---

CHANGES.rst
crate/operator/data/cratedb_large_translogs-collector.yaml
crate/operator/data/sql-exporter.yaml

Implement logic to monitor shards with unexpectedly large translogs. By default, the [translog.flush_threshold_size](https://cratedb.com/docs/crate/reference/en/latest/sql/statements/create-table.html#translog-flush-threshold-size) is set to 512 MiB. Under normal operations, translogs should not grow (significantly) larger than this.

Add translog size monitoring collector to sql_exporter

---

CHANGES.rst
crate/operator/handlers/handle_ping_cratedb_status.py
crate/operator/scale.py
tests/conftest.py
tests/test_ping_cratedb_status.py

This improves the `ping_cratedb_status` handler by catching transient errors (like ClientConnectorError and TimeoutError) and logs them as warnings instead of raising unhandled exceptions.
I also had to upgrade black to support match-case syntax.

Handle transient errors gracefully in health check

---

.pre-commit-config.yaml
CHANGES.rst
crate/operator/create.py
crate/operator/kube_auth.py
crate/operator/restore_backup.py
pyproject.toml

Bump black to latest version

---

.readthedocs.yml
CHANGES.rst
Dockerfile
crate/operator/config.py
docs/source/conf.py
docs/source/development.rst
setup.py

This PR downgrades the project’s Python version from 3.13 to 3.12 to work around SSL certificate verification issues with AKS k8s API introduced in Python 3.13. The issue appears to stem from stricter behavior in urllib3, which is pulled in indirectly by dependencies
```
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier
```

Downgrade Python to 3.12 due to SSL issues

---

CHANGES.rst
crate/operator/operations.py
tests/test_restart_cluster.py

- Temporarily set `cluster.routing.allocation.enable` to `new_primaries` before deleting each pod and reset it after the pod has restarted. This ensures more controlled shard allocation during rolling restarts.

Set cluster allocation settings during rolling restarts

---

CHANGES.rst
crate/operator/config.py

With the introduction of CrateDB node decommissioning, node shutdown can take significantly longer. To prevent premature failure of rolling restarts or scaling operations, the following operator timeouts have been increased to 4 hours:
- `ROLLING_RESTART_TIMEOUT`
- `SCALING_TIMEOUT`
- `CLUSTER_UPDATE_TIMEOUT`
This ensures sufficient time for cluster operations that involve decommissioning nodes before shutdown, especially under higher load or larger cluster sizes.

Increase timeouts for rolling restarts, scaling, and updates to 4h

---

CHANGES.rst
crate/operator/create.py
crate/operator/grand_central.py
crate/operator/handlers/handle_create_cratedb.py
tests/test_create.py

This change ensures that the `app.kubernetes.io/managed-by` label is always set to `"crate-operator"`, even if a conflicting value is provided via the CrateDB CRD.
- Introduced `build_cratedb_labels()` helper function to standardize labels across CrateDB components.
- Replaced ad-hoc label dict creation in `handle_create_cratedb.py`, `grand_central.py`, and other places with calls to `build_cratedb_labels()`.

Ensure operator overrides user-provided `managed-by` label

---

CHANGES.rst
crate/operator/constants.py
crate/operator/handlers/handle_update_cratedb.py
crate/operator/upgrade.py
tests/test_upgrade.py

This PR introduces additional safety checks and maintenance steps for major CrateDB version upgrades:
- Detection of tables requiring re-indexing
- Before performing a major version upgrade, the operator now queries the cluster to detect tables that need re-indexing based on their Lucene version. The minimum required Lucene version is determined dynamically depending on the target CrateDB version. If such tables are found, the upgrade fails with a clear error message.
- Automatic re-creation of internal tables
- After a successful major upgrade, internal CrateDB tables that may have been created with an older major version are automatically re-created to ensure compatibility and prevent warnings in the Admin UI, where internal tables would otherwise appear as needing re-indexing before …

Detect and re-create tables during major version upgrades

---

CHANGES.rst
setup.py

This PR downgrades `kopf` to `v1.37.1`. We are currently affected by a regression tracked in [nolar/kopf#1158](https://github.com/nolar/kopf/issues/1158). Until this issue is resolved upstream, our operator fails to run correctly on newer versions.

Downgrade kopf due to compatibility issue
